# Generated by Django 4.0.2 on 2023-07-17 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orderer',
            fields=[
                ('orderer_id', models.AutoField(primary_key=True, serialize=False)),
                ('orderer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('orderer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_orders.orderer')),
                ('products', models.ManyToManyField(to='app_orders.Product')),
            ],
        ),
    ]
