# Generated by Django 4.0.2 on 2023-07-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
