# Generated by Django 4.0.2 on 2023-07-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0002_remove_order_orderer_name_remove_order_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderer_id',
            new_name='orderer',
        ),
    ]
