# Generated by Django 4.0.2 on 2023-07-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0008_order_products_with_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products_with_quantities',
            field=models.JSONField(default=dict),
        ),
    ]
